AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create Security Groups for EC2 Instances

Parameters:
  VPCId:
    Type: String
    Description: VPC Id

Resources:
  PublicInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for public instance
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Adjust this to your IP range for security
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PublicInstanceSecurityGroup

  PrivateInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for private instance
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicInstanceSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PrivateInstanceSecurityGroup

Outputs:
  PublicSecurityGroupId:
    Description: Public Instance EC2 Security Group Id
    Value: !Ref PublicInstanceSecurityGroup

  PrivateSecurityGroupId:
    Description: Private Instance EC2 Security Group Id
    Value: !Ref PrivateInstanceSecurityGroup
