AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create VPC

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc_group8

Outputs:
  VPCId:
    Description: VPC Id
    Value: !Ref VPC
